# Generated by Django 6.0.5 on 2026-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
