# Generated by Django 6.0.5 on 2026-05-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_drop_landmark_ride_pickup_landmark'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ride',
            table='rides',
        ),
    ]
