# Generated by Django 6.0.5 on 2026-05-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FULL', 'Full')], default='ACTIVE', max_length=20),
        ),
    ]
